db:
  # 数据库地址(指定到数据库名) 例:  jdbc:mysql://10.0.0.69:9000/demo
  url:
  # 数据库用户名(最好使用ROOT, 使用其他用户需要有访问 information_schema 的权限)
  user:
  # 数据库密码
  password:
  # 数据库名
  databaseName:
  # 输出路径 (绝对路径) 例: D:\workspace\project\src\main\java\com\ex\group\project1\entity\po
  outputPath:
  # 目标包全名 例: com.ex.group.project1.entity.po
  targetPackageFullName:
  # 枚举类包全名 例: com.ex.group.project1.entity.types
  typePackageFullName:
  # 是否启用lombok (true/false)
  enableLombok:
  # 写入模式 all(重写所有实体类) only-new(只写入新增的表【不包括字段变化】) only-update(只更新已存在的实体类)
  writeFileMode:
